### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Lepiloff** [chuanenlin/autoturk#1]
Hello! Then run format.py I get IndexError: list index out of range 
`Traceback (most recent call last):
  File "format.py", line 16, in <module>
    x_center = float(line[1]) * x_scale
IndexError: list index out of range
`
Can you help deal with this error?

**Comment by chuanenlin** [comment]
I'm guessing that you have empty .txt files and the program is trying to get the second line of the empty file with `line[1]` which does not exist. Perhaps check if all your label files are properly labeled. :)

**Comment by paul-gege** [comment]
The first lines for all your label text files contains a count for the number of objects you placed a bounding box around. The current code doesn't account for that, to fix this just insert an **if** statement after line 14 - `if(l == 0): continue `. This skips that first line for all the files. 

After, change all the indices from lines 16-19. They should start from `line[0]` all the way to `line[3]` instead. Those are the changes I made that worked for me.
