### ISSUE TITLE
Issue in format.py 

### ISSUE THREAD

**Issue by 1udaypatil1** [chuanenlin/autoturk#2]
>>> lines = [line.rstrip('\n') for line in open('frame26.txt')]
>>> lines
['1', '42 86 433 473']    
// Above is the lines output

//Below is code snippet from format.py
num_lines = len(lines)
       for l in range(num_lines):
           line = lines[l].split()
           x_center = float(line[1]) * x_scale
           y_center = float(line[2]) * y_scale
           x_width = float(line[3]) * x_scale
           y_width = float(line[4]) * y_scale

//And hence it throws list index out of range below error
Traceback (most recent call last):
  File "format.py", line 16, in <module>
    x_center = float(line[1]) * x_scale
IndexError: list index out of range

PS: I produced labels using BBox Tool as mentioned in the tutorial.
Please let me know if my BBox label is producing wrong output.

**Comment by robin271828** [comment]
I had the same issue. I solved it by changing it to:

from PIL import Image

if __name__ == '__main__':
   file_list = [line.rstrip('\n') for line in open("/home/robinschmid/object_classifier/BBox-Label-Tool/Labels/001/labels.list")]
   num_file = len(file_list)
   for i in range(num_file):
       im = Image.open("/home/robinschmid/object_classifier/data/color/" + file_list[i][:-4] + ".jpg")
       width, height = im.size
       x_scale = 1./width
       y_scale = 1./height
       label_file = open("/home/robinschmid/object_classifier/data/yolo/" + file_list[i], "a")
       lines = [line.rstrip('\n') for line in open("/home/robinschmid/object_classifier/BBox-Label-Tool/Labels/001/" + file_list[i])]
       num_lines = len(lines)
       print("Formatted " + file_list[i])
       line = lines[1].split()
       x_center = float(line[0]) * x_scale
       y_center = float(line[1]) * y_scale
       x_width = float(line[2]) * x_scale
       y_width = float(line[3]) * y_scale
       label_file.write("0 " + str(x_center) + " " + str(y_center) + " " + str(x_width) + " " + str(y_width))
       print("0 " + str(x_center) + " " + str(y_center) + " " + str(x_width) + " " + str(y_width) + "\n")
